import { MouseEventHandler, ComponentType } from "react"
import { CSSProperties } from "styled-components"

export enum IconSizes {
    Tiny = 8,
    XXSmall = 11,
    ExtraSmall = 12,
    Small = 16,
    Default = 22,
    Large = 32,
    ExtraLarge = 48,
    Huge = 64
}

export type IconProps = {
    icon: Icons,
    width?: number,
    height?: number,
    size?: IconSizes,
    color?: string,
    style?: CSSProperties,
    iconStyle?: CSSProperties,
    className?: string,
    onClick?: MouseEventHandler<HTMLSpanElement>,
    ariaLabel?: string
}

export type IconComponent = ComponentType<Partial<IconProps> & {
    fill?: string
}>

//TODO: came up with better icon names structure
export enum Icons {
    'AppStore' = 'AppStore',
    'ArrowDown' = 'ArrowDown',
    'ArrowDownLong' = 'ArrowDownLong',
    'ArrowLeft' = 'ArrowLeft',
    'ArrowLeftLong' = 'ArrowLeftLong',
    'ArrowUpLong' = 'ArrowUpLong',
    'ArrowRight' = 'ArrowRight',
    'ArrowRightLong' = 'ArrowRightLong',
    'ArrowUp' = 'ArrowUp',
    'Bank' = 'Bank',
    'Barometern' = 'Barometern',
    'BarometernSquare' = 'BarometernSquare',
    'Blt' = 'Blt',
    'BltSquare' = 'BltSquare',
    'Bookmark' = 'Bookmark',
    'Bookmarked' = 'Bookmarked',
    'Borasdaily' = 'Borasdaily',
    'BorasdailySquare' = 'BorasdailySquare',
    'Bt' = 'Bt',
    'BTFotboll' = 'BTFotboll',
    'BTFotbollSquare' = 'BTFotbollSquare',
    'BtSquare' = 'BtSquare',
    'Calendar' = 'Calendar',
    'Camera' = 'Camera',
    'Celebration' = 'Celebration',
    'Chat' = 'Chat',
    'Checkmark' = 'Checkmark',
    'CheckmarkCircle' = 'CheckmarkCircle',
    'Church' = 'Church',
    'Cross' = 'Cross',
    'Edit' = 'Edit',
    'Enlarge' = 'Enlarge',
    'Eye' = 'Eye',
    'EyeStrikethrough' = 'EyeStrikethrough',
    'Facebook' = 'Facebook',
    'GooglePlay' = 'GooglePlay',
    'Images' = 'Images',
    'Info' = 'Info',
    'Invoice' = 'Invoice',
    'Instagram' = 'Instagram',
    'Klarna' = 'Klarna',
    'Kalmarposten' = 'Kalmarposten',
    'KalmarpostenSquare' = 'KalmarpostenSquare',
    'Klt' = 'Klt',
    'KltSquare' = 'KltSquare',
    'Key' = 'Key',
    'Kristianstadsbladet' = 'Kristianstadsbladet',
    'KristianstadsbladetSquare' = 'KristianstadsbladetSquare',
    'Languages' = 'Languages',
    'Link' = 'Link',
    'Linkedin' = 'Linkedin',
    'Location' = 'Location',
    'Mail' = 'Mail',
    'MailBox' = 'MailBox',
    'Mastercard' = 'Mastercard',
    'Menu' = 'Menu',
    'Meraalvesta' = 'Meraalvesta',
    'MeraalvestaSquare' = 'MeraalvestaSquare',
    'Meraljungby' = 'Meraljungby',
    'MeraljungbySquare' = 'MeraljungbySquare',
    'Meranaringsliv' = 'Meranaringsliv',
    'MeranaringslivSquare' = 'MeranaringslivSquare',
    'Meraosterlen' = 'Meraosterlen',
    'MeraosterlenSquare' = 'MeraosterlenSquare',
    'MinBoll' = 'MinBoll',
    'MinBollSquare' = 'MinBollSquare',
    'MinHockey' = 'MinHockey',
    'MinHockeySquare' = 'MinHockeySquare',
    'MosaikKristianstadsbladet' = 'MosaikKristianstadsbladet',
    'MosaikKristianstadsbladetSquare' = 'MosaikKristianstadsbladetSquare',
    'MosaikVXONews' = 'MosaikVXONews',
    'MosaikVXONewsSquare' = 'MosaikVXONewsSquare',
    'NewWindow' = 'NewWindow',
    'NoCircleUser' = 'NoCircleUser',
    'NoPaper' = 'NoPaper',
    'Nsk' = 'Nsk',
    'NskSquare' = 'NskSquare',
    'Olandsbladet' = 'Olandsbladet',
    'OlandsbladetSquare' = 'OlandsbladetSquare',
    'Ostralenmagasinet' = 'Ostralenmagasinet',
    'OstralenmagasinetSquare' = 'OstralenmagasinetSquare',
    'Pause' = 'Pause',
    'Paysafecard' = 'Paysafecard',
    'Phone' = 'Phone',
    'Play' = 'Play',
    'Plus' = 'Plus',
    'Print' = 'Print',
    'Quote' = 'Quote',
    'RSS' = 'RSS',
    'Search' = 'Search',
    'Settings' = 'Settings',
    'Share' = 'Share',
    'Shrink' = 'Shrink',
    'SmartPhone' = 'SmartPhone',
    'Smalandsposten' = 'Smalandsposten',
    'SmalandspostenSquare' = 'SmalandspostenSquare',
    'Swish' = 'Swish',
    'Sydostran' = 'Sydostran',
    'SydostranSquare' = 'SydostranSquare',
    'TrashCan' = 'TrashCan',
    'Trelleborgsallehanda' = 'Trelleborgsallehanda',
    'TrelleborgsallehandaSquare' = 'TrelleborgsallehandaSquare',
    'Twitter' = 'Twitter',
    'User' = 'User',
    'UT' = 'UT',
    'UTSquare' = 'UTSquare',
    'Visa' = 'Visa',
    'VaxjobladetKronobergaren' = 'VaxjobladetKronobergaren',
    'VaxjobladetKronobergarenSquare' = 'VaxjobladetKronobergarenSquare',
    'VXOWeek' = 'VXOWeek',
    'VXOWeekSquare' = 'VXOWeekSquare',
    'Ystadsallehanda' = 'Ystadsallehanda',
    'YstadsallehandaSquare' = 'YstadsallehandaSquare',
    'HejKristianstad' = 'HejKristianstad',
    'Clock' = 'Clock'
}