name: NPM Publish

on:
  push:
    tags:
    - '**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v3
    - name: build and test
      run: |
        npm i
        npm test
        npm run build
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/**
        
  publish:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - name: code checkout
      uses: actions/checkout@v3

    - name: download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist/

      # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Publish
      run: |
        npm run finalize-package
        cd dist
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}